name: build-aliyun

on:
  push:
    branches:
      - master

concurrency:
  group: build-aliyun
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        registry:
          - registry.cn-hangzhou.aliyuncs.com
          - registry.cn-wulanchabu.aliyuncs.com

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ matrix.registry }}/xingrz/vapourcontainers-runtime:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
